### ISSUE TITLE
Scraping artist without description

### ISSUE THREAD

**Issue by neenkah** [sodascience/artscraper#25]
Artists with no description (i.e. [this one](https://artsandculture.google.com/entity/esther-teichmann/g113vf7r7v)) don't get scraped.

Output shows the following:

![image](https://github.com/sodascience/artscraper/assets/33253983/fc994066-f517-437b-8e6c-ec6e050495b7)

**Comment by J535D165** [comment]
Thanks @neenkah, we will look into this!

**Comment by neenkah** [comment]
Using the same artist gives the following error because of `artist_dir = output_dir + '/' + scraper.get_wikipedia_article_title()`:

![image](https://github.com/sodascience/artscraper/assets/33253983/cfb8c943-a4c7-4d1a-811c-32e704a29ff6)
