### ISSUE TITLE
Scraping artist without English Wikipedia page

### ISSUE THREAD

**Issue by neenkah** [sodascience/artscraper#26]
Artist directory and information isn't saved when the available wikipedia page is not in English. (i.e. for [this artist](https://artsandculture.google.com/entity/cornelis-albertus-johannes-schermer/g11bw5_6rgd))

Shows the following output:
![image](https://github.com/sodascience/artscraper/assets/33253983/a3d82e18-c86d-475c-ae11-4d1a220091bb)

**Comment by modhurita** [comment]
Hi @neenkah :

I have addressed both the issues (#25 and #26) that you posted, and the changes are now merged into main. Can you please check if the scraper now works for you?

Thanks,
Modhurita

**Comment by neenkah** [comment]
It works! Artists with non-English wiki pages now get scraped
