### ISSUE TITLE
Filename too long error

### ISSUE THREAD

**Issue by neenkah** [sodascience/artscraper#28]
On Linux

![image](https://github.com/sodascience/artscraper/assets/33253983/ca25423b-26dd-457a-afa1-4f26281f885c)

This happened with the following artworks:
[artwork 1](https://artsandculture.google.com/asset/maestrapeace-detail-of-lesbian-couple-mural-on-the-san-francisco-women-s-building-18th-and-valencia-streets-juana-alicia-edythe-boone-miranda-bergman-susan-cervantes-meera-desai-yvonne-littleton-and-irene-perez-%C2%A9-1994-2000-2010-juana-alicia-edythe-boone-miranda-bergman-susan-cervantes-meera-desai-yvonne-littleton-and-irene-perez/cgEsw3X5NVcwXw)
[artwork 2](https://artsandculture.google.com/asset/maestrapeace-lapidge-street-fa%C3%A7ade-mural-on-the-san-francisco-women-s-building-18th-and-valencia-streets-juana-alicia-edythe-boone-miranda-bergman-susan-cervantes-meera-desai-yvonne-littleton-and-irene-perez-%C2%A9-1994-2000-2010-juana-alicia-edythe-boone-miranda-bergman-susan-cervantes-meera-desai-yvonne-littleton-and-irene-perez/EgGfNVyaG8m0Tg)
[artwork 3](https://artsandculture.google.com/asset/maestrapeace-corner-view-mural-on-the-san-francisco-women-s-building-18th-and-valencia-streets-juana-alicia-edythe-boone-miranda-bergman-susan-cervantes-meera-desai-yvonne-littleton-and-irene-perez-%C2%A9-1994-2000-2010-juana-alicia-edythe-boone-miranda-bergman-susan-cervantes-meera-desai-yvonne-littleton-and-irene-perez/AQHbiHz-OyvNdQ)

**Comment by modhurita** [comment]
Hi @neenkah:

This issue is now resolved and too-long filenames shouldn't cause problems any longer.
